big_doc = {
    b'_force_collection': False,
    b'_id': b'000E8F-E1308AQS000137',
    b'cpeid': b'000E8F-E1308AQS000137',
    b'last_update': {
        b'$date': 1429004949430
    },
    b'lastmsg': {
        b'$date': 1429004949420
    },
    b'metadata': {
        b'CPEModel': b'Sercomm_AD1018',
        b'IMS_login': b'user@test.com',
        b'Inet_Dhcp': b'DHCP',
        b'Observaciones': b'',
        b'SBCPrimary': b'200.100.200.100',
        b'SBCPrimary_nombre': b'SBC7',
        b'SBCSecundario': b'200.100.200.111',
        b'SBCSecundario_nombre': b'SBC5',
        b'Zone': b'ZONA-1',
        b'actual_compl': {b'$date': 1392310920000},
        b'actual_rel_date': {b'$date': 1392310920000},
        b'administrativo': b'12345',
        b'all': b'ALL',
        b'bad_forwards': 0,
        b'capacidad': b'123aa_123bb_123cc_123dd_eee',
        b'cdc': b'example_cdc',
        b'central': b'1234567',
        b'collector_name': b'lb_7547',
        b'current_time': b'2015-04-14T12:49:09',
        b'cwmpid': b'26',
        b'deleted_tag': None,
        b'discovery_failed': 0,
        b'do_not_monitor': b'False',
        b'do_not_monitor_observaciones': b'FD_TOMA_1',
        b'dslam_card': b'example_dslam_card',
        b'dslam_olt_sector': b'example_dslam_olt_sector',
        b'estado_de_cliente': b'AC',
        b'fecha_activacion': {b'$date': 1393459200000},
        b'fecha_desactivacion': b'',
        b'first_contact_time': {b'$date': 1393372800000},
        b'firstmsg': {b'$date': 1418221575816},
        b'ims_estado': b'NOT-AVAILABLE',
        b'ims_numero': b'123456789',
        b'ims_password': b'1A2B3C',
        b'ims_routing_label': b'NOT-AVAILABLE',
        b'inform_action': 3,
        b'ip': b'200.100.50.70',
        b'ip_bbras': b'10.200.1.30',
        b'ip_dinamica': b'PR',
        b'ip_fija': b'NO',
        b'ip_voz': b'200.20.100.150',
        b'last_activation_time': {b'$date': 1393372800000},
        b'last_boot_time': {b'$date': 1428911348503},
        b'last_contact_time': {b'$date': 1428883200000},
        b'login': b'user_login',
        b'modalidad': b'PAR VACANTE',
        b'msisdn': b'123456789',
        b'paquete': b'PAQUETE',
        b'password': b'111ABC',
        b'password_telnet': b'222ABC',
        b'product': b'ADSL UNIFICADO',
        b'product_class': b'AD1018',
        b'project_identification': b'EXAMPLE_PROJECT',
        b'provincia': b'MADRID',
        b'retry_count': 0,
        b'root_object': b'InternetGatewayDevice.',
        b'service_id': b'example_id',
        b'service_type': b'example_type',
        b'sidc_date': {b'$date': 1428922548448},
        b'sip': b'NO',
        b'subtipo_de_cliente': b'SIN IAE',
        b'task': b'ACT AIMS',
        b'task_status': b'Complete',
        b'territorio': b'NOT-AVAILABLE',
        b'tipo_de_accesso': b'ACCESO DIRECTO (AD)',
        b'tipo_de_cliente': b'PARTICULARES',
        b'tipo_par': b'MULTIDSL',
        b'vag': b'NO',
        b'vdsl': b'NO',
        b'velocidad': b'20MB',
        b'vf': {
            b'BR_1': 21210572,
            b'BR_2': 0,
            b'BR_3': 0,
            b'BS_1': 379150009,
            b'BS_2': 0,
            b'BS_3': 0,
            b'CRC_1': 421,
            b'EBR_211': 0,
            b'EBR_221': 23104,
            b'EBR_231': 666137537,
            b'EBS_211': 0,
            b'EBS_221': 18190,
            b'EBS_231': 56698004,
            b'EPR_211': 0,
            b'EPR_221': 33,
            b'EPR_231': 594447,
            b'EPS_211': 0,
            b'EPS_221': 34,
            b'EPS_231': 379150,
            b'Err_1': 280,
            b'FEC_1': 295307,
            b'HEC_1': 5728,
            b'IErr_1': 1,
            b'ITO_1': 1,
            b'LOF_1': 0,
            b'NUMC_1': 1,
            b'PMNOE_1': 0,
            b'PMNOE_2': 0,
            b'PMNOE_3': 0,
            b'PR_1': 156105,
            b'PR_2': 0,
            b'PR_3': 0,
            b'PS_1': 333090,
            b'PS_2': 0,
            b'PS_3': 0,
            b'SErr_1': 0,
            b'lan': {
                b'TBR': 35671019,
                b'TBS': 295267256,
                b'TPR': 244555,
                b'TPS': 331785,
                b'UT': 93742,
                b'WLANSER': 1,
                b'WLANSES': 3572
            },
            b'last_boot_time': {b'$date': 1428911348503},
            b'metadata': {
                b'last_boot_time': {b'$date': 1418464069310}
            },
            b'ts': {b'$date': 1429004954619},
            b'voice': {
                b'ARIJ': 0,
                b'ICA': 0,
                b'ICC': 0,
                b'ICF': 1,
                b'ICR': 1,
                b'OCA': 0,
                b'OCAN': 0,
                b'OCC': 0,
                b'OCF': 0,
                b'PL': 0,
                b'PR': 0,
                b'PS': 0
            }
        },
        b'vf_apply_profile_details': b'SUCCESS'
    },
    b'mode': b'AD1018',
    b'mode_props': {
        b'vf': {
            b'AUN': b'user2@test.com',
            b'CLT': b'2015-04-14 11:49:13',
            b'CRC_DIARIO': 158,
            b'DM': b'Auto',
            b'Enable': b'Enabled',
            b'LANDS': b'',
            b'MBR': b'Auto',
            b'MCU': b'MDAwRThGLUFEMTAxOC1FMTMwOEFRUzAwMDEzNw==',
            b'MN': b'AD1018',
            b'MU': b'http://www.example.com:8080/test/example',
            b'NUMC_DIARIO': 0,
            b'PMNOE_1': 0,
            b'PMNOE_2': 0,
            b'PMNOE_3': 0,
            b'PSCU': b'3.96%',
            b'TS': b'',
            b'URI': b'+34910023824',
            b'VoiceS': b'Up',
            b'WANMT': b'ADSL_2plus',
            b'WANS_1': b'Up',
            b'WLANS_1': b'Up',
            b'alarmed1_CDC': False,
            b'alarmed1_DSLAMCard': False,
            b'alarmed1_DSLAMOlSec': False,
            b'alarmed1_Prov': False,
            b'alarmed1_Zone': False,
            b'alarmed2_CDC': False,
            b'alarmed2_DSLAMCard': False,
            b'alarmed2_DSLAMOlSec': False,
            b'alarmed2_Prov': False,
            b'alarmed2_Zone': False,
            b'alarmed3_CDC': False,
            b'alarmed3_DSLAMCard': False,
            b'alarmed3_DSLAMOlSec': False,
            b'alarmed3_Prov': False,
            b'alarmed3_Zone': False,
            b'alarmed4_CDC': False,
            b'alarmed4_DSLAMCard': False,
            b'alarmed4_DSLAMOlSec': False,
            b'alarmed4_Prov': False,
            b'alarmed4_Zone': False,
            b'alarmed5_CDC': False,
            b'alarmed5_DSLAMCard': False,
            b'alarmed5_DSLAMOlSec': False,
            b'alarmed5_Prov': False,
            b'alarmed5_SBCPrimary': False,
            b'alarmed5_Zone': False,
            b'alarmed6_CDC': False,
            b'alarmed6_DSLAMCard': False,
            b'alarmed6_DSLAMOlSec': False,
            b'alarmed6_Prov': False,
            b'alarmed6_SBCPrimary': False,
            b'alarmed6_Zone': False,
            b'alarmed7_CPEModel': False,
            b'alarmed8_CPEModel': False,
            b'drop2': {
                b'BEST_DA': 19,
                b'BEST_UA': 11,
                b'MSF': 18364,
                b'MST': 59640,
                b'PSCU_remap': 3.96,
                b'REIE': b'1',
                b'VLE': 1,
                b'VLS': 1
            },
            b'lan': {
                b'BR_sum': 0,
                b'BS_sum': 0.0364837646484375,
                b'DSE': b'1',
                b'ETH': 0,
                b'FNOE': 0,
                b'HNOE': 0,
                b'HOMEPLUG': 0,
                b'HOMEPNA': 0,
                b'LANS_count': 1,
                b'MOCA': 0,
                b'OTHS': 0,
                b'PR_sum': 0,
                b'PS_sum': 134,
                b'QNOE': 17,
                b'TS_remap': 5,
                b'USB': 0,
                b'UT': 26.039444444444449,
                b'WACE_1': b'1',
                b'WIFI': 0,
                b'WLANC_1': 1,
                b'WLANRE': b'1',
                b'WLANSER': 1,
                b'WLANSES': 3572,
                b'WLANS_1_remap': 0,
                b'WPS': b'1'
            },
            b'rang': {
                b'UC1R2RGD': b'21000',
                b'UC1R2RGDD': [
                    b'21000',
                    20436,
                    12,
                    b'AVG',
                    b'D',
                    b'UC1R2RGDD_value'
                ],
                b'UC1R2RGDM': [
                    b'21000',
                    20279.68421052632,
                    323,
                    b'AVG',
                    b'M',
                    b'UC1R2RGDM_value'
                ],
                b'UC1R2RGDW': [
                    b'21000',
                    20392.28571428571,
                    35,
                    b'AVG',
                    b'W',
                    b'UC1R2RGDW_value'
                ],
                b'UC1R2RGU': b'1100',
                b'UC1R2RGUD': [
                    b'1100',
                    1070,
                    12,
                    b'AVG',
                    b'D',
                    b'UC1R2RGUD_value'
                ],
                b'UC1R2RGUM': [
                    b'1100',
                    1059.8854489164089,
                    323,
                    b'AVG',
                    b'M',
                    b'UC1R2RGUM_value'
                ],
                b'UC1R2RGUW': [
                    b'1100',
                    1067.1714285714279,
                    35,
                    b'AVG',
                    b'W',
                    b'UC1R2RGUW_value'
                ],
                b'UC1R6RGD': [
                    b'0,5',
                    0.084201080724596977,
                    12,
                    b'SUM',
                    b'D',
                    b'UC1R6RGD_value'
                ],
                b'UC1R6RGM': [
                    b'70',
                    62.239072213880718,
                    323,
                    b'SUM',
                    b'M',
                    b'UC1R6RGM_value'
                ],
                b'UC1R6RGW': [
                    b'1',
                    0.73759927414357662,
                    35,
                    b'SUM',
                    b'W',
                    b'UC1R6RGW_value'
                ],
                b'UC1R8RGE': b'0',
                b'UC1R8RGED': [
                    b'0',
                    0,
                    12,
                    b'AVG',
                    b'D',
                    b'UC1R8RGED_value'
                ],
                b'UC1R8RGEM': [
                    b'01',
                    0.30340557275541818,
                    323,
                    b'AVG',
                    b'M',
                    b'UC1R8RGEM_value'
                ],
                b'UC1R8RGEW': [
                    b'01',
                    0.085714285714285715,
                    35,
                    b'AVG',
                    b'W',
                    b'UC1R8RGEW_value'
                ],
                b'UC1R8RGW': b'0',
                b'UC1R8RGWD': [
                    b'01',
                    0.75,
                    12,
                    b'AVG',
                    b'D',
                    b'UC1R8RGWD_value'
                ],
                b'UC1R8RGWM': [
                    b'02',
                    1.6160990712074299,
                    323,
                    b'AVG',
                    b'M',
                    b'UC1R8RGWM_value'
                ],
                b'UC1R8RGWW': [
                    b'02',
                    1.514285714285714,
                    35,
                    b'AVG',
                    b'W',
                    b'UC1R8RGWW_value'
                ],
                b'periodos': [14, 16, 4]
            },
            b'roll1_win': [0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
            b'roll2_win': [0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
            b'roll4_win': [0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
            b'uc4_status': b'',
            b'vf': {
                b'diff': {
                    b'BR_1': 0,
                    b'BR_2': 0,
                    b'BR_3': 0,
                    b'BS_1': 38256,
                    b'BS_2': 0,
                    b'BS_3': 0,
                    b'CRC_1': 15,
                    b'EBR_211': 0,
                    b'EBR_221': 1515,
                    b'EBR_231': 35904,
                    b'EBS_211': 0,
                    b'EBS_221': 1188,
                    b'EBS_231': 55799,
                    b'EPR_211': 0,
                    b'EPR_221': 2,
                    b'EPR_231': 294,
                    b'EPS_211': 0,
                    b'EPS_221': 2,
                    b'EPS_231': 183,
                    b'Err_1': 10,
                    b'FEC_1': 8527,
                    b'HEC_1': 257,
                    b'IErr_1': 0,
                    b'ITO_1': 0,
                    b'LOF_1': 0,
                    b'NUMC_1': 0,
                    b'PR_1': 0,
                    b'PR_2': 0,
                    b'PR_3': 0,
                    b'PS_1': 134,
                    b'PS_2': 0,
                    b'PS_3': 0,
                    b'SErr_1': 0,
                    b'lan': {
                        b'TBR': 0,
                        b'TBS': 0.03699493408203125,
                        b'TPR': 0,
                        b'TPS': 134,
                        b'WLANSER': 0,
                        b'WLANSES': 0
                    },
                    b'voice': {
                        b'ICA': 0,
                        b'ICC': 0,
                        b'ICF': 0,
                        b'ICR': 0,
                        b'OCA': 0,
                        b'OCAN': 0,
                        b'OCC': 0,
                        b'OCF': 0
                    }
                }
            },
            b'voice': {
                b'ARIJ': 0,
                b'CD': 0,
                b'ConfStat_NewRemap_1': b'Up',
                b'Enable_remap': 0,
                b'ICFR': -1,
                b'OCFR': -1,
                b'PL': 0,
                b'PPP_1': b'1',
                b'PR': 0,
                b'PS': 0,
                b'TCT': 0,
                b'TimeStatus_NewRemap': b'Undefined',
                b'VoiceLineStatus_NewRemap': b'Up',
                b'VoiceLine_NewRemap': b'Up',
                b'VoiceS_remap': 0,
                b'report5_issue': 0,
                b'report6_issue': 0,
                b'report7_issue': 0,
                b'report8_issue': 0
            },
            b'wan': {
                b'BEST_DCR': 20436,
                b'BEST_UCR': 1083,
                b'CRC': 15,
                b'DA': 19,
                b'DA_rollw': [19, 19, 19],
                b'DCR': 20436,
                b'DCR_rollw': [20436, 20436, 20436],
                b'DMR': 23576,
                b'DM_remap': 2,
                b'DSNR': 2.2000000000000002,
                b'EBR_sum': 0.035685539245605469,
                b'EBS_sum': 0.054347038269042969,
                b'EPR_sum': 296,
                b'EPS_sum': 185,
                b'Err': 280,
                b'FEC': 295307,
                b'HEC': 5728,
                b'IErr': 1,
                b'ITO': 1,
                b'LOF': 0,
                b'MBR_remap': 4,
                b'NUMC': 0,
                b'PMNOE_sum': 0,
                b'SErr': 0,
                b'SR': -1,
                b'UA': 12,
                b'UA_rollw': [12, 12, 12],
                b'UCR': 1070,
                b'UCR_rollw': [1070, 1070, 1070],
                b'UMR': 1063,
                b'USNR': 1.1000000000000001,
                b'WANMT_remap': 4,
                b'WAN_DS_value': b'200.100.200.50,200.100.100.90',
                b'WAN_DS_value_rang': b'200_100_200_50,200_100_100_90',
                b'report1_issue': 0,
                b'report2_issue': 0,
                b'report3_issue': 0,
                b'report4_issue': 0
            }
        },
        b'vf_time': {b'$date': 1429004954619}
    },
    b'next_forward': {b'$date': 1429030145989},
    b'original_pie': True,
    b'original_pii': 86410,
    b'pii_set': 3600,
    b'pii_to_set': 3600,
    b'props': {
        b'DI': {
            b'HV': b'AD1018v1',
            b'M': b'SERCOMM',
            b'MO': b'000E8F',
            b'PC': b'AD1018',
            b'PrC': b'TR03.1110.0000',
            b'SN': b'E1308AQS000137',
            b'SV': b'v2.0.08',
            b'SpV': b'1.0'
        },
        b'DS': b'InternetGatewayDevice:1.0[](Baseline:1, EthernetLAN:1, WiFiLAN:0, GPONWAN:1, Time:1, IPPing:1)',
        b'MS': {
            b'CRU': b'http://200.100.50.70:5555/test/index.html',
             b'PIE': b'1',
             b'PII': b'86410',
             b'PK': b''
        },
        b'WD': {
            b'2': {
                b'WCD': {
                    b'2': {
                        b'WIC': {
                            b'1': {
                                b'EIA': b'150.20.100.150'
                            }
                        }
                    },
                    b'3': {
                        b'WIC': {
                            b'1': {
                                b'EIA': b'200.100.50.70'
                            }
                        }
                    }
                }
            }
        }
    },
    b'store_name': b'cpe_store'
}
