name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: false

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run Ruff linting
      run: |
        uv run ruff check ax_utils/ tests/ --output-format=github

    - name: Run Ruff formatting check
      run: |
        uv run ruff format --check ax_utils/ tests/

    - name: Run type checking
      run: |
        uv run mypy ax_utils/ --ignore-missing-imports

    - name: Check for common security issues
      run: |
        uv pip install bandit[toml]
        uv run bandit -r ax_utils/ -f json -o bandit-report.json || true

    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-scan-results
        path: bandit-report.json

  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Check for known vulnerabilities
      run: |
        uv pip install safety
        uv export --format requirements-txt | uv run safety check --stdin --output json --save-json safety-report.json || true

    - name: Upload vulnerability scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: vulnerability-scan-results
        path: safety-report.json
