name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: false

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run Ruff linting
      run: |
        uv run ruff check ax_utils/ tests/ --output-format=github

    - name: Run Ruff formatting check
      run: |
        uv run ruff format --check ax_utils/ tests/

    - name: Run type checking
      run: |
        uv run mypy ax_utils/ --ignore-missing-imports

    - name: Check for common security issues
      run: |
        uv pip install --system bandit[toml]
        echo "Running bandit security scan..."
        uv run bandit -r ax_utils/ -f json -o bandit-report.json || echo "Bandit scan completed (issues may have been found)"
        if [ -f bandit-report.json ]; then
          echo "Bandit report generated successfully"
          ls -la bandit-report.json
        else
          echo "No bandit report generated"
          echo '{"status": "no_report_generated"}' > bandit-report.json
        fi

    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always() && hashFiles('bandit-report.json') != ''
      with:
        name: security-scan-results
        path: bandit-report.json

  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Check for known vulnerabilities
      run: |
        uv pip install --system safety
        echo "Running safety vulnerability check..."
        uv export --format requirements-txt | uv run safety check --stdin --output json --save-json safety-report.json || echo "Safety check completed (vulnerabilities may have been found)"
        if [ -f safety-report.json ]; then
          echo "Safety report generated successfully"
          ls -la safety-report.json
        else
          echo "No safety report generated"
          echo '{"status": "no_report_generated"}' > safety-report.json
        fi

    - name: Upload vulnerability scan results
      uses: actions/upload-artifact@v4
      if: always() && hashFiles('safety-report.json') != ''
      with:
        name: vulnerability-scan-results
        path: safety-report.json
